INSERT INTO Lojas (nome, cidade, estado)
VALUES	('Loja 1', 'São Paulo', 'SP'),
		('Loja 2', 'Rio de Janeiro', 'RJ'),
		('Loja 3', 'Belo Horizonte', 'MG'),
		('Loja 4', 'Brasília', 'DF'),
		('Loja 5', 'Porto Alegre', 'RS'),
		('Loja 6', 'Recife', 'PE'),
		('Loja 7', 'Salvador', 'BA'),
		('Loja 8', 'Fortaleza', 'CE'),
		('Loja 9', 'Manaus', 'AM'),
		('Loja 10', 'Curitiba', 'PR'),
		('Loja 11', 'Belém', 'PA'),
		('Loja 12', 'Goiânia', 'GO'),
		('Loja 13', 'Campinas', 'SP'),
		('Loja 14', 'São José dos Campos', 'SP'),
		('Loja 15', 'Ribeirão Preto', 'SP'),
		('Loja 16', 'Vitória', 'ES'),
		('Loja 17', 'Florianópolis', 'SC'),
		('Loja 18', 'Cuiabá', 'MT'),
		('Loja 19', 'João Pessoa', 'PB'),
		('Loja 20', 'Maceió', 'AL'),
		('Loja 21', 'Natal', 'RN'),
		('Loja 22', 'Aracaju', 'SE'),
		('Loja 23', 'Palmas', 'TO'),
		('Loja 24', 'Teresina', 'PI'),
		('Loja 25', 'São Luís', 'MA'),
		('Loja 26', 'Campo Grande', 'MS'),
		('Loja 27', 'Belo Horizonte', 'MG'),
		('Loja 28', 'Uberlândia', 'MG'),
		('Loja 29', 'Contagem', 'MG'),
		('Loja 30', 'Juiz de Fora', 'MG'),
		('Loja 31', 'Montes Claros', 'MG'),
		('Loja 32', 'Uberaba', 'MG'),
		('Loja 33', 'Londrina', 'PR'),
		('Loja 34', 'Foz do Iguaçu', 'PR'),
		('Loja 35', 'Caxias do Sul', 'RS'),
		('Loja 36', 'Pelotas', 'RS'),
		('Loja 37', 'Cuiabá', 'MT'),
		('Loja 38', 'Vila Velha', 'ES'),
		('Loja 39', 'Camaçari', 'BA'),
		('Loja 40', 'Santos', 'SP'),
		('Loja 41', 'Osasco', 'SP'),
		('Loja 42', 'São Bernardo do Campo', 'SP'),
		('Loja 43', 'Guarulhos', 'SP'),
		('Loja 44', 'Diadema', 'SP'),
		('Loja 45', 'Taboão da Serra', 'SP'),
		('Loja 46', 'São José dos Pinhais', 'PR'),
		('Loja 47', 'Franca', 'SP'),
		('Loja 48', 'São Carlos', 'SP'),
		('Loja 49', 'Ribeirão das Neves', 'MG'),
		('Loja 50', 'Betim', 'MG'),
		('Loja 51', 'Maceió', 'AL'),
		('Loja 52', 'Macapá', 'AP'),
		('Loja 53', 'Manaus', 'AM'),
		('Loja 54', 'Salvador', 'BA'),
		('Loja 55', 'Fortaleza', 'CE'),
		('Loja 56', 'Brasília', 'DF'),
		('Loja 57', 'Vitória', 'ES'),
		('Loja 58', 'Goiânia', 'GO'),
		('Loja 59', 'São Luís', 'MA'),
		('Loja 60', 'Cuiabá', 'MT'),
		('Loja 61', 'Campo Grande', 'MS'),
		('Loja 62', 'Belo Horizonte', 'MG'),
		('Loja 63', 'Belém', 'PA'),
		('Loja 64', 'João Pessoa', 'PB'),
		('Loja 65', 'Recife', 'PE'),
		('Loja 66', 'Teresina', 'PI'),
		('Loja 67', 'Rio de Janeiro', 'RJ'),
		('Loja 68', 'Natal', 'RN'),
		('Loja 69', 'Porto Alegre', 'RS'),
		('Loja 70', 'Porto Velho', 'RO'),
		('Loja 71', 'Boa Vista', 'RR'),
		('Loja 72', 'Florianópolis', 'SC'),
		('Loja 73', 'São Paulo', 'SP'),
		('Loja 74', 'Aracaju', 'SE'),
		('Loja 75', 'Palmas', 'TO'),
		('Loja 76', 'Curitiba', 'PR'),
		('Loja 77', 'Maringá', 'PR'),
		('Loja 78', 'Londrina', 'PR'),
		('Loja 79', 'Foz do Iguaçu', 'PR'),
		('Loja 80', 'Rio Grande', 'RS'),
		('Loja 81', 'Porto Alegre', 'RS'),
		('Loja 82', 'Caxias do Sul', 'RS'),
		('Loja 83', 'Gravataí', 'RS'),
		('Loja 84', 'Pelotas', 'RS'),
		('Loja 85', 'Novo Hamburgo', 'RS'),
		('Loja 86', 'Santa Maria', 'RS'),
		('Loja 87', 'Canoas', 'RS'),
		('Loja 88', 'São Leopoldo', 'RS'),
		('Loja 89', 'Passo Fundo', 'RS'),
		('Loja 90', 'Uruguaiana', 'RS'),
		('Loja 91', 'Teresina', 'PI'),
		('Loja 92', 'Recife', 'PE'),
		('Loja 93', 'Maceió', 'AL'),
		('Loja 94', 'Aracaju', 'SE'),
		('Loja 95', 'João Pessoa', 'PB'),
		('Loja 96', 'Natal', 'RN'),
		('Loja 97', 'Fortaleza', 'CE'),
		('Loja 98', 'Belo Horizonte', 'MG'),
		('Loja 99', 'Vitória', 'ES'),
		('Loja 100', 'Belém', 'PA');
