INSERT INTO Clientes (nome, cidade, estado)
VALUES	('Julio', 'Rio de Janeiro', 'RJ'),
		('Ana', 'São Paulo', 'SP'),
		('Carlos', 'Belo Horizonte', 'MG'),
		('Paula', 'Recife', 'PE'),
		('Mateus', 'Porto Alegre', 'RS'),
		('Larissa', 'Salvador', 'BA'),
		('Gabriel', 'Fortaleza', 'CE'),
		('Carla', 'Curitiba', 'PR'),
		('Lucas', 'Belém', 'PA'),
		('Julia', 'Manaus', 'AM'),
		('Vinicius', 'Goiânia', 'GO'),
		('Maria', 'Campo Grande', 'MS'),
		('Felipe', 'Florianópolis', 'SC'),
		('Bianca', 'Cuiabá', 'MT'),
		('Rafael', 'Natal', 'RN'),
		('Letícia', 'João Pessoa', 'PB'),
		('Guilherme', 'Teresina', 'PI'),
		('Gabriela', 'Aracaju', 'SE'),
		('Fernando', 'Palmas', 'TO'),
		('João', 'São Paulo', 'SP'),
		('Maria', 'Rio de Janeiro', 'RJ'),
		('Pedro', 'Belo Horizonte', 'MG'),
		('Ana', 'Recife', 'PE'),
		('Lucas', 'Brasília', 'DF'),
		('Julia', 'Curitiba', 'PR'),
		('Mateus', 'Manaus', 'AM'),
		('Isabela', 'Belém', 'PA'),
		('Vinicius', 'Porto Alegre', 'RS'),
		('Gustavo', 'Fortaleza', 'CE'),
		('Larissa', 'Salvador', 'BA'),
		('Eduardo', 'Goiânia', 'GO'),
		('Rafael', 'Campinas', 'SP'),
		('Bianca', 'Natal', 'RN'),
		('Guilherme', 'Cuiabá', 'MT'),
		('Karina', 'Vitória', 'ES'),
		('Ricardo', 'São Luís', 'MA'),
		('Bruna', 'João Pessoa', 'PB'),
		('Murilo', 'Teresina', 'PI'),
		('Ana', 'Belo Horizonte', 'MG'),
		('José', 'São Paulo', 'SP'),
		('Lucas', 'Rio de Janeiro', 'RJ'),
		('Julia', 'Porto Alegre', 'RS'),
		('Pedro', 'Curitiba', 'PR'),
		('Camila', 'Brasília', 'DF'),
		('Ricardo', 'Fortaleza', 'CE'),
		('Fernanda', 'Salvador', 'BA'),
		('Gabriel', 'Recife', 'PE'),
		('Mariana', 'Belém', 'PA'),
		('Carlos', 'Maceió', 'AL'),
		('Juliana', 'Goiânia', 'GO'),
		('João', 'Campo Grande', 'MS'),
		('Amanda', 'Vitória', 'ES'),
		('Luciano', 'Belo Horizonte', 'MG'),
		('Carla', 'São Paulo', 'SP'),
		('Bruno', 'Rio de Janeiro', 'RJ'),
		('Fátima', 'Porto Alegre', 'RS'),
		('Renato', 'Curitiba', 'PR'),
		('Aline', 'Brasília', 'DF');