INSERT INTO Produtos (nome, categoria, preco)
VALUES	('Maçã', 'Fruta', 2.5),
		('Banana', 'Fruta', 3.0),
		('Laranja', 'Fruta', 2.3),
		('Coca-Cola', 'Bebida', 4.5),
		('Fanta', 'Bebida', 4.0),
		('Pepsi', 'Bebida', 3.5),
		('Guaraná', 'Bebida', 3.0),
		('Suco de Laranja', 'Fruta', 3.5),
		('Agua mineral', 'Bebida', 2.5),
		('Acerola', 'Fruta', 3.5),
		('Kiwi', 'Fruta', 4.0),
		('Limão', 'Fruta', 3.0),
		('Suco de uva', 'Bebida', 4.00),
		('Refrigerante de cola', 'Bebida', 3.00),
		('Cerveja', 'Bebida', 5.00),
		('Vinho', 'Bebida', 10.00),
		('Água mineral', 'Bebida', 2.00),
		('Chá gelado', 'Bebida', 3.50),
		('Café expresso', 'Bebida', 4.50),
		('Morango', 'Fruta', 3.00),
		('Mamão', 'Fruta', 2.50),
		('Cerveja artesanal', 'Bebida', 8.00),
		('Whisky', 'Bebida', 15.00),
		('Cachaça', 'Bebida', 12.00),
		('Gin', 'Bebida', 14.00),
		('Vodka', 'Bebida', 12.00),
		('Tequila', 'Bebida', 12.50),
		('Suco de Laranja', 'Bebida', 3.5),
		('Cerveja Pilsen', 'Bebida', 4.5),
		('Açaí', 'Fruta', 4.0),
		('Abacaxi', 'Fruta', 3.0),
		('Manga', 'Fruta', 2.5),
		('Chocolate quente', 'Bebida', 3.5),
		('Goiaba', 'Fruta', 2.5),
		('Limonada', 'Bebida', 2.5),
		('Tomate', 'Fruta', 2.0),
		('Pera', 'Fruta', 3.0),
		('Vinho tinto', 'Bebida', 12.0),
		('Amora', 'Fruta', 4.0);